// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks_test.go -package=aqara
//

// Package aqara is a generated GoMock package.
package aqara

import (
	context "context"
	reflect "reflect"

	aqaramcp "github.com/mshaulsky/aqaramcp"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Statuses mocks base method.
func (m *MockClient) Statuses(ctx context.Context, filter aqaramcp.StatusFilter) ([]aqaramcp.DeviceStatus, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Statuses", ctx, filter)
	ret0, _ := ret[0].([]aqaramcp.DeviceStatus)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Statuses indicates an expected call of Statuses.
func (mr *MockClientMockRecorder) Statuses(ctx, filter any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Statuses", reflect.TypeOf((*MockClient)(nil).Statuses), ctx, filter)
}

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
	isgomock struct{}
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// IncRequest mocks base method.
func (m *MockMetrics) IncRequest(source string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncRequest", source)
}

// IncRequest indicates an expected call of IncRequest.
func (mr *MockMetricsMockRecorder) IncRequest(source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncRequest", reflect.TypeOf((*MockMetrics)(nil).IncRequest), source)
}
