// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks_test.go -package=source
//

// Package source is a generated GoMock package.
package source

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/mshaulsky/domovoi/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockSource is a mock of Source interface.
type MockSource struct {
	ctrl     *gomock.Controller
	recorder *MockSourceMockRecorder
	isgomock struct{}
}

// MockSourceMockRecorder is the mock recorder for MockSource.
type MockSourceMockRecorder struct {
	mock *MockSource
}

// NewMockSource creates a new mock instance.
func NewMockSource(ctrl *gomock.Controller) *MockSource {
	mock := &MockSource{ctrl: ctrl}
	mock.recorder = &MockSourceMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSource) EXPECT() *MockSourceMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockSource) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockSourceMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockSource)(nil).Name))
}

// Poll mocks base method.
func (m *MockSource) Poll(ctx context.Context) (Batch, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Poll", ctx)
	ret0, _ := ret[0].(Batch)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Poll indicates an expected call of Poll.
func (mr *MockSourceMockRecorder) Poll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Poll", reflect.TypeOf((*MockSource)(nil).Poll), ctx)
}

// MockWatcher is a mock of Watcher interface.
type MockWatcher struct {
	ctrl     *gomock.Controller
	recorder *MockWatcherMockRecorder
	isgomock struct{}
}

// MockWatcherMockRecorder is the mock recorder for MockWatcher.
type MockWatcherMockRecorder struct {
	mock *MockWatcher
}

// NewMockWatcher creates a new mock instance.
func NewMockWatcher(ctrl *gomock.Controller) *MockWatcher {
	mock := &MockWatcher{ctrl: ctrl}
	mock.recorder = &MockWatcherMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWatcher) EXPECT() *MockWatcherMockRecorder {
	return m.recorder
}

// Watch mocks base method.
func (m *MockWatcher) Watch(ctx context.Context, sink Sink) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", ctx, sink)
	ret0, _ := ret[0].(error)
	return ret0
}

// Watch indicates an expected call of Watch.
func (mr *MockWatcherMockRecorder) Watch(ctx, sink any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockWatcher)(nil).Watch), ctx, sink)
}

// MockSink is a mock of Sink interface.
type MockSink struct {
	ctrl     *gomock.Controller
	recorder *MockSinkMockRecorder
	isgomock struct{}
}

// MockSinkMockRecorder is the mock recorder for MockSink.
type MockSinkMockRecorder struct {
	mock *MockSink
}

// NewMockSink creates a new mock instance.
func NewMockSink(ctrl *gomock.Controller) *MockSink {
	mock := &MockSink{ctrl: ctrl}
	mock.recorder = &MockSinkMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSink) EXPECT() *MockSinkMockRecorder {
	return m.recorder
}

// Batch mocks base method.
func (m *MockSink) Batch(source string, b Batch) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Batch", source, b)
}

// Batch indicates an expected call of Batch.
func (mr *MockSinkMockRecorder) Batch(source, b any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Batch", reflect.TypeOf((*MockSink)(nil).Batch), source, b)
}

// Event mocks base method.
func (m *MockSink) Event(e model.Event) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Event", e)
}

// Event indicates an expected call of Event.
func (mr *MockSinkMockRecorder) Event(e any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Event", reflect.TypeOf((*MockSink)(nil).Event), e)
}

// Health mocks base method.
func (m *MockSink) Health(source string, err error) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Health", source, err)
}

// Health indicates an expected call of Health.
func (mr *MockSinkMockRecorder) Health(source, err any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Health", reflect.TypeOf((*MockSink)(nil).Health), source, err)
}

// MockController is a mock of Controller interface.
type MockController struct {
	ctrl     *gomock.Controller
	recorder *MockControllerMockRecorder
	isgomock struct{}
}

// MockControllerMockRecorder is the mock recorder for MockController.
type MockControllerMockRecorder struct {
	mock *MockController
}

// NewMockController creates a new mock instance.
func NewMockController(ctrl *gomock.Controller) *MockController {
	mock := &MockController{ctrl: ctrl}
	mock.recorder = &MockControllerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockController) EXPECT() *MockControllerMockRecorder {
	return m.recorder
}

// Set mocks base method.
func (m *MockController) Set(ctx context.Context, device model.DeviceID, metric model.Metric, v model.Value) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Set", ctx, device, metric, v)
	ret0, _ := ret[0].(error)
	return ret0
}

// Set indicates an expected call of Set.
func (mr *MockControllerMockRecorder) Set(ctx, device, metric, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Set", reflect.TypeOf((*MockController)(nil).Set), ctx, device, metric, v)
}

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
	isgomock struct{}
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// IncPollError mocks base method.
func (m *MockMetrics) IncPollError(source string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncPollError", source)
}

// IncPollError indicates an expected call of IncPollError.
func (mr *MockMetricsMockRecorder) IncPollError(source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncPollError", reflect.TypeOf((*MockMetrics)(nil).IncPollError), source)
}

// IncPollSuccess mocks base method.
func (m *MockMetrics) IncPollSuccess(source string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncPollSuccess", source)
}

// IncPollSuccess indicates an expected call of IncPollSuccess.
func (mr *MockMetricsMockRecorder) IncPollSuccess(source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncPollSuccess", reflect.TypeOf((*MockMetrics)(nil).IncPollSuccess), source)
}

// ObservePollDuration mocks base method.
func (m *MockMetrics) ObservePollDuration(source string, d time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObservePollDuration", source, d)
}

// ObservePollDuration indicates an expected call of ObservePollDuration.
func (mr *MockMetricsMockRecorder) ObservePollDuration(source, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObservePollDuration", reflect.TypeOf((*MockMetrics)(nil).ObservePollDuration), source, d)
}
