// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks_test.go -package=core
//

// Package core is a generated GoMock package.
package core

import (
	context "context"
	reflect "reflect"
	time "time"

	model "github.com/mshaulsky/domovoi/internal/model"
	gomock "go.uber.org/mock/gomock"
)

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
	isgomock struct{}
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// IncEvent mocks base method.
func (m *MockMetrics) IncEvent(kind string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncEvent", kind)
}

// IncEvent indicates an expected call of IncEvent.
func (mr *MockMetricsMockRecorder) IncEvent(kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncEvent", reflect.TypeOf((*MockMetrics)(nil).IncEvent), kind)
}

// IncStoreError mocks base method.
func (m *MockMetrics) IncStoreError(op string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncStoreError", op)
}

// IncStoreError indicates an expected call of IncStoreError.
func (mr *MockMetricsMockRecorder) IncStoreError(op any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncStoreError", reflect.TypeOf((*MockMetrics)(nil).IncStoreError), op)
}

// MockStore is a mock of Store interface.
type MockStore struct {
	ctrl     *gomock.Controller
	recorder *MockStoreMockRecorder
	isgomock struct{}
}

// MockStoreMockRecorder is the mock recorder for MockStore.
type MockStoreMockRecorder struct {
	mock *MockStore
}

// NewMockStore creates a new mock instance.
func NewMockStore(ctrl *gomock.Controller) *MockStore {
	mock := &MockStore{ctrl: ctrl}
	mock.recorder = &MockStoreMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStore) EXPECT() *MockStoreMockRecorder {
	return m.recorder
}

// Persist mocks base method.
func (m *MockStore) Persist(ctx context.Context, devices []model.Device, readings []model.Reading, events []model.Event, at time.Time) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Persist", ctx, devices, readings, events, at)
	ret0, _ := ret[0].(error)
	return ret0
}

// Persist indicates an expected call of Persist.
func (mr *MockStoreMockRecorder) Persist(ctx, devices, readings, events, at any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Persist", reflect.TypeOf((*MockStore)(nil).Persist), ctx, devices, readings, events, at)
}

// Prune mocks base method.
func (m *MockStore) Prune(ctx context.Context, before time.Time) (int64, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Prune", ctx, before)
	ret0, _ := ret[0].(int64)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Prune indicates an expected call of Prune.
func (mr *MockStoreMockRecorder) Prune(ctx, before any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Prune", reflect.TypeOf((*MockStore)(nil).Prune), ctx, before)
}

// Restore mocks base method.
func (m *MockStore) Restore(ctx context.Context) ([]model.Device, []model.Reading, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Restore", ctx)
	ret0, _ := ret[0].([]model.Device)
	ret1, _ := ret[1].([]model.Reading)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Restore indicates an expected call of Restore.
func (mr *MockStoreMockRecorder) Restore(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Restore", reflect.TypeOf((*MockStore)(nil).Restore), ctx)
}

// MockPoller is a mock of Poller interface.
type MockPoller struct {
	ctrl     *gomock.Controller
	recorder *MockPollerMockRecorder
	isgomock struct{}
}

// MockPollerMockRecorder is the mock recorder for MockPoller.
type MockPollerMockRecorder struct {
	mock *MockPoller
}

// NewMockPoller creates a new mock instance.
func NewMockPoller(ctrl *gomock.Controller) *MockPoller {
	mock := &MockPoller{ctrl: ctrl}
	mock.recorder = &MockPollerMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockPoller) EXPECT() *MockPollerMockRecorder {
	return m.recorder
}

// Once mocks base method.
func (m *MockPoller) Once(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Once", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Once indicates an expected call of Once.
func (mr *MockPollerMockRecorder) Once(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Once", reflect.TypeOf((*MockPoller)(nil).Once), ctx)
}

// Run mocks base method.
func (m *MockPoller) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockPollerMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockPoller)(nil).Run), ctx)
}

// MockCoordinator is a mock of Coordinator interface.
type MockCoordinator struct {
	ctrl     *gomock.Controller
	recorder *MockCoordinatorMockRecorder
	isgomock struct{}
}

// MockCoordinatorMockRecorder is the mock recorder for MockCoordinator.
type MockCoordinatorMockRecorder struct {
	mock *MockCoordinator
}

// NewMockCoordinator creates a new mock instance.
func NewMockCoordinator(ctrl *gomock.Controller) *MockCoordinator {
	mock := &MockCoordinator{ctrl: ctrl}
	mock.recorder = &MockCoordinatorMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCoordinator) EXPECT() *MockCoordinatorMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockCoordinator) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockCoordinatorMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockCoordinator)(nil).Name))
}

// NextPage mocks base method.
func (m *MockCoordinator) NextPage() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "NextPage")
}

// NextPage indicates an expected call of NextPage.
func (mr *MockCoordinatorMockRecorder) NextPage() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextPage", reflect.TypeOf((*MockCoordinator)(nil).NextPage))
}

// Refresh mocks base method.
func (m *MockCoordinator) Refresh() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Refresh")
}

// Refresh indicates an expected call of Refresh.
func (mr *MockCoordinatorMockRecorder) Refresh() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockCoordinator)(nil).Refresh))
}

// Render mocks base method.
func (m *MockCoordinator) Render(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Render indicates an expected call of Render.
func (mr *MockCoordinatorMockRecorder) Render(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockCoordinator)(nil).Render), ctx)
}

// Run mocks base method.
func (m *MockCoordinator) Run(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Run", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Run indicates an expected call of Run.
func (mr *MockCoordinatorMockRecorder) Run(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Run", reflect.TypeOf((*MockCoordinator)(nil).Run), ctx)
}

// Wake mocks base method.
func (m *MockCoordinator) Wake() {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "Wake")
}

// Wake indicates an expected call of Wake.
func (mr *MockCoordinatorMockRecorder) Wake() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Wake", reflect.TypeOf((*MockCoordinator)(nil).Wake))
}

// MockCommands is a mock of Commands interface.
type MockCommands struct {
	ctrl     *gomock.Controller
	recorder *MockCommandsMockRecorder
	isgomock struct{}
}

// MockCommandsMockRecorder is the mock recorder for MockCommands.
type MockCommandsMockRecorder struct {
	mock *MockCommands
}

// NewMockCommands creates a new mock instance.
func NewMockCommands(ctrl *gomock.Controller) *MockCommands {
	mock := &MockCommands{ctrl: ctrl}
	mock.recorder = &MockCommandsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockCommands) EXPECT() *MockCommandsMockRecorder {
	return m.recorder
}

// Acknowledge mocks base method.
func (m *MockCommands) Acknowledge(alertID int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Acknowledge", alertID)
	ret0, _ := ret[0].(error)
	return ret0
}

// Acknowledge indicates an expected call of Acknowledge.
func (mr *MockCommandsMockRecorder) Acknowledge(alertID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Acknowledge", reflect.TypeOf((*MockCommands)(nil).Acknowledge), alertID)
}

// AcknowledgeAll mocks base method.
func (m *MockCommands) AcknowledgeAll() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AcknowledgeAll")
	ret0, _ := ret[0].(error)
	return ret0
}

// AcknowledgeAll indicates an expected call of AcknowledgeAll.
func (mr *MockCommandsMockRecorder) AcknowledgeAll() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AcknowledgeAll", reflect.TypeOf((*MockCommands)(nil).AcknowledgeAll))
}

// Mute mocks base method.
func (m *MockCommands) Mute(d time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Mute", d)
	ret0, _ := ret[0].(error)
	return ret0
}

// Mute indicates an expected call of Mute.
func (mr *MockCommandsMockRecorder) Mute(d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Mute", reflect.TypeOf((*MockCommands)(nil).Mute), d)
}

// NextPage mocks base method.
func (m *MockCommands) NextPage(display string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "NextPage", display)
	ret0, _ := ret[0].(error)
	return ret0
}

// NextPage indicates an expected call of NextPage.
func (mr *MockCommandsMockRecorder) NextPage(display any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "NextPage", reflect.TypeOf((*MockCommands)(nil).NextPage), display)
}

// Refresh mocks base method.
func (m *MockCommands) Refresh(display string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Refresh", display)
	ret0, _ := ret[0].(error)
	return ret0
}

// Refresh indicates an expected call of Refresh.
func (mr *MockCommandsMockRecorder) Refresh(display any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Refresh", reflect.TypeOf((*MockCommands)(nil).Refresh), display)
}

// Reload mocks base method.
func (m *MockCommands) Reload() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Reload")
	ret0, _ := ret[0].(error)
	return ret0
}

// Reload indicates an expected call of Reload.
func (mr *MockCommandsMockRecorder) Reload() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Reload", reflect.TypeOf((*MockCommands)(nil).Reload))
}
