// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks_test.go -package=render
//

// Package render is a generated GoMock package.
package render

import (
	context "context"
	image "image"
	reflect "reflect"
	time "time"

	display "github.com/mshaulsky/domovoi/internal/display"
	i18n "github.com/mshaulsky/domovoi/internal/i18n"
	model "github.com/mshaulsky/domovoi/internal/model"
	scene "github.com/mshaulsky/domovoi/internal/scene"
	state "github.com/mshaulsky/domovoi/internal/state"
	gomock "go.uber.org/mock/gomock"
)

// MockDisplay is a mock of Display interface.
type MockDisplay struct {
	ctrl     *gomock.Controller
	recorder *MockDisplayMockRecorder
	isgomock struct{}
}

// MockDisplayMockRecorder is the mock recorder for MockDisplay.
type MockDisplayMockRecorder struct {
	mock *MockDisplay
}

// NewMockDisplay creates a new mock instance.
func NewMockDisplay(ctrl *gomock.Controller) *MockDisplay {
	mock := &MockDisplay{ctrl: ctrl}
	mock.recorder = &MockDisplayMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockDisplay) EXPECT() *MockDisplayMockRecorder {
	return m.recorder
}

// Show mocks base method.
func (m *MockDisplay) Show(ctx context.Context, f display.Frame) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Show", ctx, f)
	ret0, _ := ret[0].(error)
	return ret0
}

// Show indicates an expected call of Show.
func (mr *MockDisplayMockRecorder) Show(ctx, f any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Show", reflect.TypeOf((*MockDisplay)(nil).Show), ctx, f)
}

// Surface mocks base method.
func (m *MockDisplay) Surface() display.Surface {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Surface")
	ret0, _ := ret[0].(display.Surface)
	return ret0
}

// Surface indicates an expected call of Surface.
func (mr *MockDisplayMockRecorder) Surface() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Surface", reflect.TypeOf((*MockDisplay)(nil).Surface))
}

// MockScene is a mock of Scene interface.
type MockScene struct {
	ctrl     *gomock.Controller
	recorder *MockSceneMockRecorder
	isgomock struct{}
}

// MockSceneMockRecorder is the mock recorder for MockScene.
type MockSceneMockRecorder struct {
	mock *MockScene
}

// NewMockScene creates a new mock instance.
func NewMockScene(ctrl *gomock.Controller) *MockScene {
	mock := &MockScene{ctrl: ctrl}
	mock.recorder = &MockSceneMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockScene) EXPECT() *MockSceneMockRecorder {
	return m.recorder
}

// Name mocks base method.
func (m *MockScene) Name() string {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Name")
	ret0, _ := ret[0].(string)
	return ret0
}

// Name indicates an expected call of Name.
func (mr *MockSceneMockRecorder) Name() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Name", reflect.TypeOf((*MockScene)(nil).Name))
}

// Render mocks base method.
func (m *MockScene) Render(s display.Surface, v scene.View) (*image.Paletted, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Render", s, v)
	ret0, _ := ret[0].(*image.Paletted)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Render indicates an expected call of Render.
func (mr *MockSceneMockRecorder) Render(s, v any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Render", reflect.TypeOf((*MockScene)(nil).Render), s, v)
}

// MockHistory is a mock of History interface.
type MockHistory struct {
	ctrl     *gomock.Controller
	recorder *MockHistoryMockRecorder
	isgomock struct{}
}

// MockHistoryMockRecorder is the mock recorder for MockHistory.
type MockHistoryMockRecorder struct {
	mock *MockHistory
}

// NewMockHistory creates a new mock instance.
func NewMockHistory(ctrl *gomock.Controller) *MockHistory {
	mock := &MockHistory{ctrl: ctrl}
	mock.recorder = &MockHistoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockHistory) EXPECT() *MockHistoryMockRecorder {
	return m.recorder
}

// Events mocks base method.
func (m *MockHistory) Events(ctx context.Context, since time.Time, limit int) ([]model.Event, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Events", ctx, since, limit)
	ret0, _ := ret[0].([]model.Event)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Events indicates an expected call of Events.
func (mr *MockHistoryMockRecorder) Events(ctx, since, limit any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Events", reflect.TypeOf((*MockHistory)(nil).Events), ctx, since, limit)
}

// Extremes mocks base method.
func (m_2 *MockHistory) Extremes(ctx context.Context, id model.DeviceID, m model.Metric, since time.Time) (float64, float64, bool, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Extremes", ctx, id, m, since)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(float64)
	ret2, _ := ret[2].(bool)
	ret3, _ := ret[3].(error)
	return ret0, ret1, ret2, ret3
}

// Extremes indicates an expected call of Extremes.
func (mr *MockHistoryMockRecorder) Extremes(ctx, id, m, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Extremes", reflect.TypeOf((*MockHistory)(nil).Extremes), ctx, id, m, since)
}

// Trend mocks base method.
func (m_2 *MockHistory) Trend(ctx context.Context, id model.DeviceID, m model.Metric, since time.Time) (float64, bool, error) {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "Trend", ctx, id, m, since)
	ret0, _ := ret[0].(float64)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Trend indicates an expected call of Trend.
func (mr *MockHistoryMockRecorder) Trend(ctx, id, m, since any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Trend", reflect.TypeOf((*MockHistory)(nil).Trend), ctx, id, m, since)
}

// MockLocale is a mock of Locale interface.
type MockLocale struct {
	ctrl     *gomock.Controller
	recorder *MockLocaleMockRecorder
	isgomock struct{}
}

// MockLocaleMockRecorder is the mock recorder for MockLocale.
type MockLocaleMockRecorder struct {
	mock *MockLocale
}

// NewMockLocale creates a new mock instance.
func NewMockLocale(ctrl *gomock.Controller) *MockLocale {
	mock := &MockLocale{ctrl: ctrl}
	mock.recorder = &MockLocaleMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockLocale) EXPECT() *MockLocaleMockRecorder {
	return m.recorder
}

// Bundle mocks base method.
func (m *MockLocale) Bundle() *i18n.Bundle {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Bundle")
	ret0, _ := ret[0].(*i18n.Bundle)
	return ret0
}

// Bundle indicates an expected call of Bundle.
func (mr *MockLocaleMockRecorder) Bundle() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Bundle", reflect.TypeOf((*MockLocale)(nil).Bundle))
}

// Location mocks base method.
func (m *MockLocale) Location() *time.Location {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Location")
	ret0, _ := ret[0].(*time.Location)
	return ret0
}

// Location indicates an expected call of Location.
func (mr *MockLocaleMockRecorder) Location() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Location", reflect.TypeOf((*MockLocale)(nil).Location))
}

// MockStateReader is a mock of StateReader interface.
type MockStateReader struct {
	ctrl     *gomock.Controller
	recorder *MockStateReaderMockRecorder
	isgomock struct{}
}

// MockStateReaderMockRecorder is the mock recorder for MockStateReader.
type MockStateReaderMockRecorder struct {
	mock *MockStateReader
}

// NewMockStateReader creates a new mock instance.
func NewMockStateReader(ctrl *gomock.Controller) *MockStateReader {
	mock := &MockStateReader{ctrl: ctrl}
	mock.recorder = &MockStateReaderMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockStateReader) EXPECT() *MockStateReaderMockRecorder {
	return m.recorder
}

// Snapshot mocks base method.
func (m *MockStateReader) Snapshot(now time.Time) state.Snapshot {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Snapshot", now)
	ret0, _ := ret[0].(state.Snapshot)
	return ret0
}

// Snapshot indicates an expected call of Snapshot.
func (mr *MockStateReaderMockRecorder) Snapshot(now any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Snapshot", reflect.TypeOf((*MockStateReader)(nil).Snapshot), now)
}

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
	isgomock struct{}
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// IncRender mocks base method.
func (m *MockMetrics) IncRender(arg0, mode string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncRender", arg0, mode)
}

// IncRender indicates an expected call of IncRender.
func (mr *MockMetricsMockRecorder) IncRender(arg0, mode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncRender", reflect.TypeOf((*MockMetrics)(nil).IncRender), arg0, mode)
}

// IncRenderError mocks base method.
func (m *MockMetrics) IncRenderError(arg0 string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncRenderError", arg0)
}

// IncRenderError indicates an expected call of IncRenderError.
func (mr *MockMetricsMockRecorder) IncRenderError(arg0 any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncRenderError", reflect.TypeOf((*MockMetrics)(nil).IncRenderError), arg0)
}

// ObserveRenderDuration mocks base method.
func (m *MockMetrics) ObserveRenderDuration(arg0 string, d time.Duration) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "ObserveRenderDuration", arg0, d)
}

// ObserveRenderDuration indicates an expected call of ObserveRenderDuration.
func (mr *MockMetricsMockRecorder) ObserveRenderDuration(arg0, d any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ObserveRenderDuration", reflect.TypeOf((*MockMetrics)(nil).ObserveRenderDuration), arg0, d)
}
