// Code generated by MockGen. DO NOT EDIT.
// Source: interfaces.go
//
// Generated by this command:
//
//	mockgen -source=interfaces.go -destination=mocks_test.go -package=tuya
//

// Package tuya is a generated GoMock package.
package tuya

import (
	context "context"
	reflect "reflect"

	tuyacloud "github.com/mshaulsky/tuyacloud"
	gomock "go.uber.org/mock/gomock"
)

// MockClient is a mock of Client interface.
type MockClient struct {
	ctrl     *gomock.Controller
	recorder *MockClientMockRecorder
	isgomock struct{}
}

// MockClientMockRecorder is the mock recorder for MockClient.
type MockClientMockRecorder struct {
	mock *MockClient
}

// NewMockClient creates a new mock instance.
func NewMockClient(ctrl *gomock.Controller) *MockClient {
	mock := &MockClient{ctrl: ctrl}
	mock.recorder = &MockClientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockClient) EXPECT() *MockClientMockRecorder {
	return m.recorder
}

// Devices mocks base method.
func (m *MockClient) Devices(ctx context.Context) ([]tuyacloud.Device, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Devices", ctx)
	ret0, _ := ret[0].([]tuyacloud.Device)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Devices indicates an expected call of Devices.
func (mr *MockClientMockRecorder) Devices(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Devices", reflect.TypeOf((*MockClient)(nil).Devices), ctx)
}

// DevicesStatus mocks base method.
func (m *MockClient) DevicesStatus(ctx context.Context, deviceIDs ...string) (map[string]tuyacloud.Status, error) {
	m.ctrl.T.Helper()
	varargs := []any{ctx}
	for _, a := range deviceIDs {
		varargs = append(varargs, a)
	}
	ret := m.ctrl.Call(m, "DevicesStatus", varargs...)
	ret0, _ := ret[0].(map[string]tuyacloud.Status)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DevicesStatus indicates an expected call of DevicesStatus.
func (mr *MockClientMockRecorder) DevicesStatus(ctx any, deviceIDs ...any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	varargs := append([]any{ctx}, deviceIDs...)
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DevicesStatus", reflect.TypeOf((*MockClient)(nil).DevicesStatus), varargs...)
}

// Specification mocks base method.
func (m *MockClient) Specification(ctx context.Context, deviceID string) (tuyacloud.Specification, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Specification", ctx, deviceID)
	ret0, _ := ret[0].(tuyacloud.Specification)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Specification indicates an expected call of Specification.
func (mr *MockClientMockRecorder) Specification(ctx, deviceID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Specification", reflect.TypeOf((*MockClient)(nil).Specification), ctx, deviceID)
}

// MockMetrics is a mock of Metrics interface.
type MockMetrics struct {
	ctrl     *gomock.Controller
	recorder *MockMetricsMockRecorder
	isgomock struct{}
}

// MockMetricsMockRecorder is the mock recorder for MockMetrics.
type MockMetricsMockRecorder struct {
	mock *MockMetrics
}

// NewMockMetrics creates a new mock instance.
func NewMockMetrics(ctrl *gomock.Controller) *MockMetrics {
	mock := &MockMetrics{ctrl: ctrl}
	mock.recorder = &MockMetricsMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMetrics) EXPECT() *MockMetricsMockRecorder {
	return m.recorder
}

// IncRequest mocks base method.
func (m *MockMetrics) IncRequest(source string) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "IncRequest", source)
}

// IncRequest indicates an expected call of IncRequest.
func (mr *MockMetricsMockRecorder) IncRequest(source any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "IncRequest", reflect.TypeOf((*MockMetrics)(nil).IncRequest), source)
}
